yarnPath: .yarn/releases/yarn-0.0.1-git.20220426.hash-a30b37d.cjs

packageExtensions:
  '@strapi/admin@*':
    dependencies:
      object-assign: '*'
      whatwg-fetch: '*'
      react-is: '*'
  '@strapi/plugin-email@*':
    dependencies:
      '@strapi/helper-plugin': '*'
